# Generated by Django 5.2.8 on 2025-12-19 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0005_productgroup_tags'),
        ('users', '0007_rename_phone_address_recipient_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_discount_percent', models.PositiveIntegerField(default=0, verbose_name='Скидка по заказу (%)')),
                ('delivery_service', models.CharField(blank=True, max_length=50, verbose_name='Служба доставки')),
                ('delivery_tariff', models.CharField(blank=True, max_length=80, verbose_name='Тариф/код тарифа')),
                ('discount_type', models.CharField(choices=[('bonuses', 'Только бонусы'), ('discount', 'Только скидка'), ('semi_bonuses', 'Скидка и бонусы')], default='discount', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Активная'), ('converted', 'Оформлена в заказ'), ('abandoned', 'Брошена')], default='active', max_length=20)),
                ('delivery_type', models.CharField(choices=[('courier', 'Курьер'), ('pickup_point', 'Пункт выдачи'), ('self_pickup', 'Самовывоз')], default='courier', max_length=20)),
                ('delivery_price', models.PositiveIntegerField(default=0, verbose_name='Цена доставки')),
                ('pickup_point_code', models.CharField(blank=True, max_length=120)),
                ('pickup_point_address', models.CharField(blank=True, max_length=255)),
                ('pickup_point_provider', models.CharField(blank=True, max_length=50)),
                ('payment_type', models.CharField(choices=[('card', 'Банковской картой'), ('sbp', 'СБП'), ('invoice', 'Счет на оплату')], default='card', max_length=20)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('items_subtotal', models.PositiveIntegerField(default=0, verbose_name='Сумма товаров (без доставки)')),
                ('discount_total', models.PositiveIntegerField(default=0, verbose_name='Скидка всего')),
                ('bonuses_spent_total', models.PositiveIntegerField(default=0, verbose_name='Списано бонусов по заказу')),
                ('bonuses_append_total', models.PositiveIntegerField(default=0, verbose_name='Начислено бонусов по заказу')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Итого к оплате')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='users.address', verbose_name='Выбранный адрес')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('current_unit_price', models.PositiveIntegerField(default=0)),
                ('current_unit_price_discounted', models.PositiveIntegerField(default=0)),
                ('bonuses_append', models.PositiveIntegerField(default=0, verbose_name='Начислить бонусов по позиции')),
                ('bonuses_spent', models.PositiveIntegerField(default=0, verbose_name='Списать бонусов по позиции')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='shop.product')),
            ],
            options={
                'verbose_name': 'Позиция корзины',
                'verbose_name_plural': 'Позиции корзины',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
