# Generated by Django 5.2.8 on 2025-12-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cartitem_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pickup_point_address',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pickup_point_code',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pickup_point_provider',
        ),
    ]
