# Generated by Django 5.2.8 on 2025-12-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_cart_pickup_point_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Банковской картой'), ('sbp', 'СБП'), ('invoice', 'Счет на оплату')], default='sbp', max_length=20),
        ),
    ]
