# Generated by Django 5.2.8 on 2025-12-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cart_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='line_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Итоговая сумма по позиции'),
        ),
    ]
