# Generated by Django 5.2.8 on 2025-12-26 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cartitem_line_total'),
        ('users', '0010_requisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='requisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='users.requisites', verbose_name='Реквизиты для счета'),
        ),
    ]
