# Generated by Django 5.2.8 on 2026-03-18 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cart_requisites'),
        ('shop', '0006_alter_instruction_product'),
        ('users', '0016_alter_userphone_options_userphone_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'РљРѕСЂР·РёРЅР°', 'verbose_name_plural': 'РљРѕСЂР·РёРЅС‹'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'РџРѕР·РёС†РёСЏ РєРѕСЂР·РёРЅС‹', 'verbose_name_plural': 'РџРѕР·РёС†РёРё РєРѕСЂР·РёРЅС‹'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='users.address', verbose_name='Р’С‹Р±СЂР°РЅРЅС‹Р№ Р°РґСЂРµСЃ'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='bonuses_append_total',
            field=models.PositiveIntegerField(default=0, verbose_name='РќР°С‡РёСЃР»РµРЅРѕ Р±РѕРЅСѓСЃРѕРІ РїРѕ Р·Р°РєР°Р·Сѓ'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='bonuses_spent_total',
            field=models.PositiveIntegerField(default=0, verbose_name='РЎРїРёСЃР°РЅРѕ Р±РѕРЅСѓСЃРѕРІ РїРѕ Р·Р°РєР°Р·Сѓ'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='comment',
            field=models.TextField(blank=True, verbose_name='РљРѕРјРјРµРЅС‚Р°СЂРёР№ Рє Р·Р°РєР°Р·Сѓ'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Р¦РµРЅР° РґРѕСЃС‚Р°РІРєРё'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_service',
            field=models.CharField(blank=True, max_length=50, verbose_name='РЎР»СѓР¶Р±Р° РґРѕСЃС‚Р°РІРєРё'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_tariff',
            field=models.CharField(blank=True, max_length=80, verbose_name='РўР°СЂРёС„/РєРѕРґ С‚Р°СЂРёС„Р°'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_type',
            field=models.CharField(choices=[('courier', 'РљСѓСЂСЊРµСЂ'), ('pickup_point', 'РџСѓРЅРєС‚ РІС‹РґР°С‡Рё'), ('self_pickup', 'РЎР°РјРѕРІС‹РІРѕР·')], default='courier', max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount_total',
            field=models.PositiveIntegerField(default=0, verbose_name='РЎРєРёРґРєР° РІСЃРµРіРѕ'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount_type',
            field=models.CharField(choices=[('bonuses', 'РўРѕР»СЊРєРѕ Р±РѕРЅСѓСЃС‹'), ('discount', 'РўРѕР»СЊРєРѕ СЃРєРёРґРєР°'), ('semi_bonuses', 'РЎРєРёРґРєР° Рё Р±РѕРЅСѓСЃС‹')], default='discount', max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items_subtotal',
            field=models.PositiveIntegerField(default=0, verbose_name='РЎСѓРјРјР° С‚РѕРІР°СЂРѕРІ (Р±РµР· РґРѕСЃС‚Р°РІРєРё)'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='РЎРєРёРґРєР° РїРѕ Р·Р°РєР°Р·Сѓ (%)'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Р‘Р°РЅРєРѕРІСЃРєРѕР№ РєР°СЂС‚РѕР№'), ('sbp', 'РЎР‘Рџ'), ('invoice', 'РЎС‡РµС‚ РЅР° РѕРїР»Р°С‚Сѓ')], default='sbp', max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='requisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='users.requisites', verbose_name='Р\xa0РµРєРІРёР·РёС‚С‹ РґР»СЏ СЃС‡РµС‚Р°'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'РђРєС‚РёРІРЅР°СЏ'), ('converted', 'РћС„РѕСЂРјР»РµРЅР° РІ Р·Р°РєР°Р·'), ('abandoned', 'Р‘СЂРѕС€РµРЅР°')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Р\x98С‚РѕРіРѕ Рє РѕРїР»Р°С‚Рµ'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='bonuses_append',
            field=models.PositiveIntegerField(default=0, verbose_name='РќР°С‡РёСЃР»РёС‚СЊ Р±РѕРЅСѓСЃРѕРІ РїРѕ РїРѕР·РёС†РёРё'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='bonuses_spent',
            field=models.PositiveIntegerField(default=0, verbose_name='РЎРїРёСЃР°С‚СЊ Р±РѕРЅСѓСЃРѕРІ РїРѕ РїРѕР·РёС†РёРё'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='line_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Р\x98С‚РѕРіРѕРІР°СЏ СЃСѓРјРјР° РїРѕ РїРѕР·РёС†РёРё'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_discount_percent', models.PositiveIntegerField(default=0, verbose_name='РЎРєРёРґРєР° РїРѕ Р·Р°РєР°Р·Сѓ (%)')),
                ('comment', models.TextField(blank=True, verbose_name='РљРѕРјРјРµРЅС‚Р°СЂРёР№ Рє Р·Р°РєР°Р·Сѓ')),
                ('amo_crm_id', models.IntegerField(blank=True, null=True, verbose_name='ID СЃРґРµР»РєРё РІ AMO')),
                ('items_subtotal', models.PositiveIntegerField(default=0, verbose_name='РЎСѓРјРјР° С‚РѕРІР°СЂРѕРІ (Р±РµР· РґРѕСЃС‚Р°РІРєРё)')),
                ('discount_total', models.PositiveIntegerField(default=0, verbose_name='РЎРєРёРґРєР° РІСЃРµРіРѕ')),
                ('bonuses_spent_total', models.PositiveIntegerField(default=0, verbose_name='РЎРїРёСЃР°РЅРѕ Р±РѕРЅСѓСЃРѕРІ РїРѕ Р·Р°РєР°Р·Сѓ')),
                ('bonuses_append_total', models.PositiveIntegerField(default=0, verbose_name='РќР°С‡РёСЃР»РµРЅРѕ Р±РѕРЅСѓСЃРѕРІ РїРѕ Р·Р°РєР°Р·Сѓ')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Р\x98С‚РѕРіРѕ Рє РѕРїР»Р°С‚Рµ')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.address', verbose_name='Р’С‹Р±СЂР°РЅРЅС‹Р№ Р°РґСЂРµСЃ')),
                ('requisites', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.requisites', verbose_name='Р\xa0РµРєРІРёР·РёС‚С‹ РґР»СЏ СЃС‡РµС‚Р°')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ')),
            ],
            options={
                'verbose_name': 'Р—Р°РєР°Р·',
                'verbose_name_plural': 'Р—Р°РєР°Р·С‹',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('current_unit_price', models.PositiveIntegerField(default=0)),
                ('current_unit_price_discounted', models.PositiveIntegerField(default=0)),
                ('bonuses_append', models.PositiveIntegerField(default=0, verbose_name='РќР°С‡РёСЃР»РёС‚СЊ Р±РѕРЅСѓСЃРѕРІ РїРѕ РїРѕР·РёС†РёРё')),
                ('bonuses_spent', models.PositiveIntegerField(default=0, verbose_name='РЎРїРёСЃР°С‚СЊ Р±РѕРЅСѓСЃРѕРІ РїРѕ РїРѕР·РёС†РёРё')),
                ('line_total', models.PositiveIntegerField(default=0, verbose_name='Р\x98С‚РѕРіРѕРІР°СЏ СЃСѓРјРјР° РїРѕ РїРѕР·РёС†РёРё')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.product')),
            ],
            options={
                'verbose_name': 'РџРѕР·РёС†РёСЏ Р·Р°РєР°Р·Р°',
                'verbose_name_plural': 'РџРѕР·РёС†РёРё Р·Р°РєР°Р·Р°',
            },
        ),
    ]
