# Generated by Django 5.2.8 on 2026-03-18 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_cart_options_alter_cartitem_options_and_more'),
        ('users', '0016_alter_userphone_options_userphone_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Позиция корзины', 'verbose_name_plural': 'Позиции корзины'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказа'},
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_service',
            field=models.CharField(blank=True, max_length=50, verbose_name='Служба доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_tariff',
            field=models.CharField(blank=True, max_length=80, verbose_name='Тариф/код тарифа'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('courier', 'Курьер'), ('pickup_point', 'Пункт выдачи'), ('self_pickup', 'Самовывоз')], default='courier', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_type',
            field=models.CharField(choices=[('bonuses', 'Только бонусы'), ('discount', 'Только скидка'), ('semi_bonuses', 'Скидка и бонусы')], default='discount', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Банковской картой'), ('sbp', 'СБП'), ('invoice', 'Счет на оплату')], default='sbp', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Активная'), ('converted', 'Оформлена в заказ'), ('abandoned', 'Брошена')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='users.address', verbose_name='Выбранный адрес'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='bonuses_append_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Начислено бонусов по заказу'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='bonuses_spent_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Списано бонусов по заказу'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена доставки'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_service',
            field=models.CharField(blank=True, max_length=50, verbose_name='Служба доставки'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_tariff',
            field=models.CharField(blank=True, max_length=80, verbose_name='Тариф/код тарифа'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_type',
            field=models.CharField(choices=[('courier', 'Курьер'), ('pickup_point', 'Пункт выдачи'), ('self_pickup', 'Самовывоз')], default='courier', max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка всего'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount_type',
            field=models.CharField(choices=[('bonuses', 'Только бонусы'), ('discount', 'Только скидка'), ('semi_bonuses', 'Скидка и бонусы')], default='discount', max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items_subtotal',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма товаров (без доставки)'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка по заказу (%)'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Банковской картой'), ('sbp', 'СБП'), ('invoice', 'Счет на оплату')], default='sbp', max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='requisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='users.requisites', verbose_name='Реквизиты для счета'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Активная'), ('converted', 'Оформлена в заказ'), ('abandoned', 'Брошена')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Итого к оплате'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='bonuses_append',
            field=models.PositiveIntegerField(default=0, verbose_name='Начислить бонусов по позиции'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='bonuses_spent',
            field=models.PositiveIntegerField(default=0, verbose_name='Списать бонусов по позиции'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='line_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Итоговая сумма по позиции'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.address', verbose_name='Выбранный адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amo_crm_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID сделки в AMO'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bonuses_append_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Начислено бонусов по заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bonuses_spent_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Списано бонусов по заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка всего'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items_subtotal',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма товаров (без доставки)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка по заказу (%)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='requisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.requisites', verbose_name='Реквизиты для счета'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Итого к оплате'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='bonuses_append',
            field=models.PositiveIntegerField(default=0, verbose_name='Начислить бонусов по позиции'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='bonuses_spent',
            field=models.PositiveIntegerField(default=0, verbose_name='Списать бонусов по позиции'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Итоговая сумма по позиции'),
        ),
    ]
