# Generated by Django 5.2.8 on 2026-04-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='need_help',
            field=models.BooleanField(default=False),
        ),
    ]
