# Generated by Django 5.2.8 on 2026-04-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_cart_need_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='need_help',
            field=models.BooleanField(default=False),
        ),
    ]
