# Generated by Django 5.2.8 on 2026-04-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_need_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amo_crm_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID сделки в AMO'),
        ),
    ]
