# Generated by Django 5.2.8 on 2026-04-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_amo_crm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='discount_type',
            field=models.CharField(choices=[('bonuses', 'Накопить бонусы'), ('discount', 'Применить скидку'), ('semi_bonuses', 'Скидка и бонусы')], default='discount', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_type',
            field=models.CharField(choices=[('bonuses', 'Накопить бонусы'), ('discount', 'Применить скидку'), ('semi_bonuses', 'Скидка и бонусы')], default='discount', max_length=20),
        ),
    ]
