# Generated by Django 5.2.8 on 2026-04-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_cart_discount_type_alter_order_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='discount_type',
            field=models.CharField(choices=[('discount', 'Применить скидку'), ('bonuses', 'Накопить бонусы'), ('semi_bonuses', 'Скидка и бонусы')], default='discount', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_type',
            field=models.CharField(choices=[('discount', 'Применить скидку'), ('bonuses', 'Накопить бонусы'), ('semi_bonuses', 'Скидка и бонусы')], default='discount', max_length=20),
        ),
    ]
