# Generated by Django 5.2.8 on 2026-05-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_cart_discount_type_alter_order_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_type',
            field=models.CharField(choices=[('courier', 'Курьер'), ('pickup_point', 'Пункт выдачи'), ('self_pickup', 'Самовывоз')], default='self_pickup', max_length=20),
        ),
    ]
