# Generated by Django 5.2.8 on 2026-06-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_alter_cart_delivery_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("courier", "Курьер"),
                    ("pickup_point", "Пункт выдачи"),
                    ("self_pickup", "Самовывоз"),
                ],
                default="pickup_point",
                max_length=20,
            ),
        ),
    ]
