# Generated by Django 5.2.8 on 2026-06-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_cart_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='related_added_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Добавлено из сопутствующих товаров'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='related_added_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Добавлено из сопутствующих товаров'),
        ),
    ]
