# Generated by Django 5.2.8 on 2025-12-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='amo_id',
            new_name='amo_id_customer',
        ),
        migrations.AddField(
            model_name='user',
            name='amo_id_contact',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID контакта в AMO'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Телеграм ID'),
        ),
    ]
