# Generated by Django 5.2.8 on 2025-12-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_amo_id_user_amo_id_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonuses',
            field=models.IntegerField(default=0, verbose_name='Бонусы на балансе'),
        ),
        migrations.AddField(
            model_name='user',
            name='buyout_per_quater',
            field=models.IntegerField(default=0, verbose_name='Сумма чистого выкупа за квартал'),
        ),
        migrations.AddField(
            model_name='user',
            name='partner_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Скидка покупателя'),
        ),
        migrations.AddField(
            model_name='user',
            name='partner_status',
            field=models.CharField(choices=[('start', 'Старт'), ('base', 'База'), ('bronze', 'Бронза'), ('silver', 'Серебро'), ('gold', 'Золото'), ('platina', 'Платина'), ('business', 'Бизнес'), ('exclusive', 'Эксклюзив')], default='start', max_length=255, verbose_name='Статус партнёра'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_buyout',
            field=models.IntegerField(default=0, verbose_name='Сумма чистого выкупа'),
        ),
    ]
