# Generated by Django 5.2.8 on 2025-12-17 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bonuses_user_buyout_per_quater_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='Адрес по умолчанию')),
                ('label', models.CharField(blank=True, help_text='Например: Дом, Офис', max_length=50, verbose_name='Название адреса')),
                ('recipient_name', models.CharField(blank=True, max_length=120, verbose_name='Получатель')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон получателя')),
                ('country', models.CharField(default='Россия', max_length=80, verbose_name='Страна')),
                ('city', models.CharField(max_length=120, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house', models.CharField(max_length=50, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, max_length=50, verbose_name='Квартира / офис')),
                ('postcode', models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс')),
                ('comment', models.TextField(blank=True, help_text='Подъезд, этаж, код домофона и т.п.', verbose_name='Комментарий для курьера')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
                'ordering': ('-is_default', '-time_created'),
            },
        ),
    ]
