# Generated by Django 5.2.8 on 2025-12-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Наименование партнёра')),
                ('amo_id_customer', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID покупателя в AMO')),
                ('partner_status', models.CharField(choices=[('start', 'Старт'), ('base', 'База'), ('bronze', 'Бронза'), ('silver', 'Серебро'), ('gold', 'Золото'), ('platina', 'Платина'), ('business', 'Бизнес'), ('exclusive', 'Эксклюзив')], default='start', max_length=255, verbose_name='Статус партнёра')),
                ('partner_discount', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Скидка покупателя')),
                ('bonuses', models.IntegerField(default=0, verbose_name='Бонусы на балансе')),
                ('total_buyout', models.IntegerField(default=0, verbose_name='Сумма чистого выкупа')),
                ('buyout_per_quater', models.IntegerField(default=0, verbose_name='Сумма чистого выкупа за квартал')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатель',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='amo_id_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bonuses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='buyout_per_quater',
        ),
        migrations.RemoveField(
            model_name='user',
            name='partner_discount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='partner_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_buyout',
        ),
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.customer', verbose_name='Покупатель'),
        ),
    ]
