# Generated by Django 5.2.8 on 2025-12-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customer_remove_user_amo_id_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='client', max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
