# Generated by Django 5.2.8 on 2025-12-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customer_options_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phone',
            new_name='recipient_phone',
        ),
    ]
