# Generated by Django 5.2.8 on 2025-12-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_phone_address_recipient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pickup_point_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='pickup_point_code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='address',
            name='pickup_point_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
