# Generated by Django 5.2.8 on 2025-12-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_address_pickup_point_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефон получателя'),
        ),
    ]
