# Generated by Django 5.2.8 on 2025-12-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_requisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='delivery_address_text',
            field=models.TextField(blank=True, max_length=455, verbose_name='Адрес доставки полный'),
        ),
    ]
