# Generated by Django 5.2.8 on 2026-01-21 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_address_delivery_address_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('email_type', models.CharField(choices=[('work', 'Рабочая'), ('other', 'Другой')], default='other', max_length=5, verbose_name='Тип почты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email пользователя',
                'verbose_name_plural': 'Email-адреса пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32, unique=True, verbose_name='Номер телефона')),
                ('phone_type', models.CharField(choices=[('work', 'Рабочий'), ('other', 'Другой')], default='other', max_length=5, verbose_name='Тип телефона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Телефон пользователя',
                'verbose_name_plural': 'Телефоны пользователей',
            },
        ),
    ]
