# Generated by Django 5.2.8 on 2026-01-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_useremail_userphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphone',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserEmail',
        ),
        migrations.DeleteModel(
            name='UserPhone',
        ),
    ]
