# Generated by Django 5.2.8 on 2026-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_userphone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="max_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="\u0422\u0435\u043b\u0435\u0433\u0440\u0430\u043c ID"),
        ),
    ]


