# Generated by Django 5.2.8 on 2026-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_max_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userphone',
            options={'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AddField(
            model_name='userphone',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='MAX ID'),
        ),
        migrations.AddConstraint(
            model_name='userphone',
            constraint=models.UniqueConstraint(fields=('phone',), name='uniq_user_phone'),
        ),
    ]
