# Generated by Django 5.2.8 on 2026-04-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_userphone_options_userphone_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amo_id_customer',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID покупателя в AMO'),
        ),
        migrations.AlterField(
            model_name='user',
            name='amo_id_contact',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID контакта в AMO'),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='MAX ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Телеграм ID'),
        ),
    ]
