# Generated by Django 5.2.8 on 2025-12-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_name_alter_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='discont',
            new_name='discount',
        ),
    ]
