# Generated by Django 5.2.8 on 2025-12-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_discont_category_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Закрепить наверху'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция в каталоге'),
        ),
    ]
