# Generated by Django 5.2.8 on 2025-12-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ManyToManyField(to='shop.image', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
    ]
