# Generated by Django 5.2.8 on 2025-12-18 10:36

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productgroup_is_pinned_productgroup_sort_order'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
