# Generated by Django 5.2.8 on 2026-01-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productgroup_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='shop.product', verbose_name='Товар'),
        ),
    ]
