# Generated by Django 5.2.8 on 2025-12-05 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_image_options_product_photo_alter_image_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Лимит покупки'),
        ),
    ]
