# Generated by Django 5.2.8 on 2026-04-16 10:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_instruction_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount_policy',
            field=models.CharField(choices=[('standard', 'Обычная'), ('status_capped', 'Лимит по статусу партнера')], default='standard', max_length=20, verbose_name='Тип расчета скидки'),
        ),
        migrations.CreateModel(
            name='CategoryStatusDiscountCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_status', models.CharField(choices=[('start', 'Старт'), ('base', 'База'), ('bronze', 'Бронза'), ('silver', 'Серебро'), ('gold', 'Золото'), ('platina', 'Платина'), ('business', 'Бизнес'), ('exclusive', 'Эксклюзив')], max_length=255, verbose_name='Статус партнера')),
                ('max_discount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Максимальная скидка (%)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_caps', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Лимит скидки по статусу',
                'verbose_name_plural': 'Лимиты скидки по статусам',
                'constraints': [models.UniqueConstraint(fields=('category', 'partner_status'), name='unique_category_partner_status_discount_cap')],
            },
        ),
    ]
