# Generated by Django 5.2.8 on 2025-12-05 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_photo_image_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='shop.product', verbose_name='Видео'),
        ),
    ]
