# Generated by Django 5.2.8 on 2026-04-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_discount_policy_categorystatusdiscountcap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amo_id',
            field=models.PositiveBigIntegerField(verbose_name='id товара в amocrm'),
        ),
    ]
