# Generated by Django 5.2.8 on 2026-04-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_amo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modification_name',
            field=models.CharField(default='Нет наименования', max_length=255, verbose_name='Наименование модификации'),
        ),
    ]
