# Generated by Django 5.2.8 on 2026-05-25 14:40

from django.db import migrations, models


def copy_video_products(apps, schema_editor):
    Video = apps.get_model('shop', 'Video')
    through_model = Video.products.through

    relations = [
        through_model(video_id=video.id, product_id=video.product_id)
        for video in Video.objects.exclude(product_id__isnull=True).only('id', 'product_id')
    ]
    through_model.objects.bulk_create(relations, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_modification_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='products',
            field=models.ManyToManyField(related_name='videos', to='shop.product', verbose_name='Товары'),
        ),
        migrations.RunPython(copy_video_products, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='video',
            name='product',
        ),
    ]
