# Generated by Django 5.2.8 on 2026-06-10 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_instruction_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок показа')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('related_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_related_product_links', to='shop.productgroup', verbose_name='Сопутствующая группа')),
                ('source_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product_links', to='shop.productgroup', verbose_name='Основная группа')),
            ],
            options={
                'verbose_name': 'Сопутствующий товар',
                'verbose_name_plural': 'Сопутствующие товары',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='productgroup',
            name='related_groups',
            field=models.ManyToManyField(blank=True, related_name='recommended_by_groups', through='shop.RelatedProductGroup', to='shop.productgroup', verbose_name='Сопутствующие товары'),
        ),
        migrations.AddConstraint(
            model_name='relatedproductgroup',
            constraint=models.UniqueConstraint(fields=('source_group', 'related_group'), name='unique_related_product_group_pair'),
        ),
        migrations.AddConstraint(
            model_name='relatedproductgroup',
            constraint=models.CheckConstraint(condition=models.Q(('source_group', models.F('related_group')), _negated=True), name='related_product_group_not_self'),
        ),
    ]
