# Generated by Django 5.2.8 on 2026-06-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_relatedproductgroup_productgroup_related_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedProductStats',
            fields=[
            ],
            options={
                'verbose_name': 'Статистика сопутствующего товара',
                'verbose_name_plural': 'Статистика сопутствующих товаров',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.product',),
        ),
    ]
